### PR TITLE
Minor style changes, made the buttons more uniform

### PR DESCRIPTION
**Pull request by EffyJohn**
No edits have been made to the core code, just added an extra CSS class and some code to make minor style changes.

### CODE REVIEW

**Comment by mehulmpt** [comment]
Can you attach an image of how it looks after your changes? I cannot see it myself because I don't have access to the PS panel where extension injects the script

**Comment by EffyJohn** [comment]
image

This is what it should look like, minus the "project details" button. That button is for accessing the project details directly from said screen without having to go to the other tab, I haven't finished implementing that yet. That was the primary intent of my editing, but I didn't get enough time to finish the code for that. I'll be pushing that sometime soon, after I've finished my list of station preferences.

**Comment by mehulmpt** [comment]
Alright, looks okay. Can you send a PR with more screenshots included? I would need them for re-publishing the extension on chrome webstore too.

Thanks

**Comment by mehulmpt** [comment]
We can work on the Project Details button too, good suggestion. Maybe discuss that in another issue?

**Pull request closed without merging**
