### PR TITLE
Just added features to the extension to move ranges and view problem bank page using a toggle iframe.

### PR DESCRIPTION
**Pull request by VidhuArnav**
I have found it to work for me.

### CODE REVIEW

**Comment by mehulmpt** [comment]
I would test the updates and would get back to you.

**Comment by VidhuArnav** [comment]
If you want screenshots of the page for web store I can send them, currently I have made a post of the fork on the bits/ps fb grp as I thought we would need it...once if you accept the request and update the version on webstore I will delete the post...the 5$ pay-wall was too much so I have told everyone to unpack it offline as guided in the original readme

**Comment by mehulmpt** [comment]
Good work with the iframe. We need to refactor the moverange a little - the alerts and UI is not very intuitive. Also, the font size is too small now, is there any reason for that?

One last thing, instead of pushing the whole iframe, can we actually use the internal API for BITS to pull out only that stations data without loading the whole page?

**Comment by VidhuArnav** [comment]
I just liked the smaller font size as I it doesn't bloat the li element, I had also fixed iframes height to 400px which is just over average height of the modal that opens on the problem banks page. So the font size was an aesthetic choice made so that atleast two three choices are visible at once, I think it doesn't look too shabby as seen here, 
Screenshot (116)

**Comment by VidhuArnav** [comment]
The API thing I have replied here #5

**Comment by VidhuArnav** [comment]
As for the move range alerts I agree that can be worked on to make it more intuitive(maybe take both inputs using one prompt and debugging them together), given time I was also thinking of having a checkbox in each li element and then providng the club and position at index feature. later versions can have it possibly.

**Comment by VidhuArnav** [comment]
I just came to know you were a batchie, I just looked you up on linkedin and YouTube. Looking at your github heatmap I was under the impression that you are a graduate who had made this extension long back 😅.

**Pull request merged**
